heat_template_version: 2013-05-23

description: |
  A template that deploys the dokku Heroku-ish PaaS onto a single Linux server.

parameters:

  flavor:
    label: Server Size
    description: |
      Rackspace Cloud Server flavor to use. The size is based on the amount of
      RAM for the provisioned server.
    type: string
    default: 2 GB Performance
    constraints:
      - allowed_values:
        - 1 GB Performance
        - 2 GB Performance
        - 4 GB Performance
        - 8 GB Performance
        - 15 GB Performance
        - 30 GB Performance
        - 1GB Standard Instance
        - 2GB Standard Instance
        - 4GB Standard Instance
        - 8GB Standard Instance
        - 15GB Standard Instance
        - 30GB Standard Instance
        description: must be a valid Rackspace Cloud Server flavor.

  image:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    constraints:
    - allowed_values:
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      description: Must be a supported operating system.

  server_name:
    label: Server Hostname
    description: The instance name
    type: string
    default: dokku

  domain:
    label: Dokku Domain Name
    description: The DNS domain where the dokku server will present applications.
    type: string
    default: example.com

  dokku_installer_location:
    label: Dokku Installer Location
    description: Location of the dokku bootstrap script.
    type: string
    default: |
      https://raw.github.com/progrium/dokku/v0.3.16/bootstrap.sh

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  dokku:
    type: "OS::Nova::Server"
    properties:
      key_name: { get_resource: ssh_key }
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: { get_param: server_name }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
      config_drive: "true"
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            package_update: true
            packages:
              - wget
            write_files:
              - path: /home/dokku/.ssh/id_dokku_client.pub
                permissions: '0600'
                content: |
                  %ssh_pub_key%
              - path: /home/dokku/VHOST
                permissions: '0444'
                content: |
                  %domain%
              - path: /tmp/heat/utils/get_latest_dokku_version
                permissions: '0555'
                content: |
                  #!/usr/bin/env python

                  import re
                  import subprocess

                  def git_lsremote_output(repo='https://github.com/progrium/dokku.git'):
                      output = subprocess.check_output(['git', 'ls-remote', '--tags', repo])
                      return output

                  if __name__ == '__main__':
                      output = git_lsremote_output()
                      for line in output.splitlines():
                          (hash, tagref) = line.split()
                          (ref, tag, version) = tagref.split('/')
                          if re.match('^v', version):
                              print version
              - path: /tmp/heat/install_dokku.sh
                permissions: '0500'
                content: |
                  #!/bin/bash -x
                  chmod 700 /home/dokku/.ssh
                  mkdir /tmp/heat
                  cd /tmp/heat
                  wget -q -O bootstrap.sh %dokku_installer_location%
                  DOKKU_TAG=v0.3.16 /usr/bin/env bash -x bootstrap.sh
                  /usr/local/bin/sshcommand acl-add dokku %dokku_client% < /home/dokku/.ssh/id_dokku_client.pub
            runcmd:
              - /tmp/heat/install_dokku.sh
          params:
            "%dokku_installer_location%": { get_param: dokku_installer_location }
            "%domain%": { get_param: domain }
            "%ssh_pub_key%": { get_attr: [ssh_key, public_key] }
            "%dokku_client%": dokku_client
outputs:
  private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }

  server_ip:
    value: { get_attr: [ dokku, accessIPv4 ] }
    description: Server IP
